### ISSUE TITLE
Invalid module name on pip install

### ISSUE THREAD

**Issue by captainfodder** [dmachard/python-pdnsbackup#93]
When installing this package via PIP, the file created at `~/.local/bin/pdnsbackup` contains invalid code.

### Issue
Running the code after install results in an error:
```bash
user@host:~$ pdnsbackup -h
Traceback (most recent call last):
  File "/home/user/.local/bin/pdnsbackup", line 5, in <module>
    from pdnsbackup.backup import run
ModuleNotFoundError: No module named 'pdnsbackup.backup'
```

### Possible Fix
I think this can be fixed by changing this line:
```python
from pdnsbackup.backup import run
```
to instead be this:
```python
from pdnsbackup import run
```

**Comment by dmachard** [comment]
thanks to report this bug, it's fixed in the release v0.11.5
